- name: 🪟 Set Windows Wallpaper via Scheduled Task Script
  hosts: windows
  gather_facts: false

  tasks:
    - name: 📄 Replace wallpaper image to new one
      win_copy:
        src: new_wallpaper.png
        dest: C:\Users\Public\Pictures\wallpaper.png
        force: yes

    - name: 📜 Copy wallpaper PowerShell script to Windows
      win_copy:
        src: set_wallpaper.ps1
        dest: C:\Users\Public\set_wallpaper.ps1

    - name: 🖼️ Run wallpaper script as logged-in user via scheduled task
      win_shell: |
        $user = "$env:COMPUTERNAME + '\' + $env:USERNAME"
        Write-Host "Running scheduled task as user: $user"

        $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument '-ExecutionPolicy Bypass -File "C:\Users\Public\set_wallpaper.ps1"'
        $principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Highest
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

        Register-ScheduledTask -TaskName "ApplyWallpaper" -Action $action -Principal $principal -Settings $settings -Force
        Start-ScheduledTask -TaskName "ApplyWallpaper"
        Start-Sleep -Seconds 5
        Unregister-ScheduledTask -TaskName "ApplyWallpaper" -Confirm:$false
      args:
        executable: powershell.exe
