---
- name: 🪟 Set Windows Wallpaper via Registry
  hosts: windows
  gather_facts: false

  tasks:
    - name: 📄 Copy wallpaper image to Windows
      win_copy:
        src: wallpaper.png
        dest: C:\Users\Public\Pictures\wallpaper.png

    - name: 🖼️ Set wallpaper via registry
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: Wallpaper
        data: C:\Users\Public\Pictures\wallpaper.png
        type: string

    - name: 🔄 Apply wallpaper using RUNDLL32
      win_shell: |
        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters 1, True
