---
- name: Set wallpaper on all GNOME-based Linux clients
  hosts: all
  become: yes
  vars:
    wallpaper_file: "wallpaper.png"
    dest_path: "/usr/share/backgrounds/{{ wallpaper_file }}"
    wallpaper_uri: "file:///usr/share/backgrounds/{{ wallpaper_file }}"

  tasks:
    - name: 📥 Copy wallpaper to client machine
      copy:
        src: "{{ wallpaper_file }}"
        dest: "{{ dest_path }}"
        mode: '0644'

    - name: 🖼 Apply wallpaper using gsettings
      become_user: root
      command: >
        gsettings set org.gnome.desktop.background picture-uri "{{ wallpaper_uri }}"
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/root/.Xauthority"
