---
- name: 🪟 Set Windows Wallpaper via Scheduled Task Script
  hosts: windows
  gather_facts: false

  tasks:
    - name: 📄 Copy wallpaper image to Windows
      win_copy:
        src: wallpaper.png
        dest: C:\Users\Public\Pictures\wallpaper.png

    - name: 📜 Copy wallpaper PowerShell script to Windows
      win_copy:
        src: set_wallpaper.ps1
        dest: C:\Users\Public\set_wallpaper.ps1

    - name: 🖼️ Run script as logged-in user via scheduled task
      win_shell: |
        $task = @{
          TaskName    = "ApplyWallpaper"
          Action      = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File 'C:\Users\Public\set_wallpaper.ps1'"
          Principal   = New-ScheduledTaskPrincipal -UserId "$env:USERNAME" -LogonType Interactive -RunLevel Highest
          Settings    = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
        }
        Register-ScheduledTask @task -Force
        Start-ScheduledTask -TaskName "ApplyWallpaper"
        Start-Sleep -Seconds 5
        Unregister-ScheduledTask -TaskName "ApplyWallpaper" -Confirm:$false
      args:
        executable: powershell.exe
