---
- name: 🪟 Set Windows Wallpaper via Scheduled Task Script
  hosts: windows
  gather_facts: false

  tasks:
    - name: 📄 Copy wallpaper image to Windows
      win_copy:
        src: wallpaper.png
        dest: C:\Users\Public\Pictures\wallpaper.png

    - name: 📜 Copy wallpaper PowerShell script to Windows
      win_copy:
        src: set_wallpaper.ps1
        dest: C:\Users\Public\set_wallpaper.ps1

    - name: 🖼️ Execute wallpaper PowerShell script
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Users\Public\set_wallpaper.ps1
