---
- name: ðŸªŸ Set Windows Wallpaper via Scheduled Task
  hosts: windows
  gather_facts: false
  vars:
    wallpaper_path: 'C:\\Users\\Public\\Pictures\\wallpaper.png'
    script_path: 'C:\\Users\\Public\\set-wallpaper.ps1'

  tasks:
    - name: ðŸ“„ Copy wallpaper image to Windows
      win_copy:
        src: wallpaper.png
        dest: "{{ wallpaper_path }}"

    - name: ðŸ“ Create PowerShell script to set wallpaper
      win_copy:
        dest: "{{ script_path }}"
        content: |
          Add-Type @"
          using System.Runtime.InteropServices;
          public class Wallpaper {
              [DllImport("user32.dll", SetLastError = true)]
              public static extern bool SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
          }
"@
          [Wallpaper]::SystemParametersInfo(20, 0, '{{ wallpaper_path }}', 3)

    - name: ðŸ—“ï¸ Create scheduled task to apply the wallpaper
      win_scheduled_task:
        name: SetWallpaperTask
        description: Set desktop wallpaper
        actions:
          - path: powershell.exe
            arguments: >
              -ExecutionPolicy Bypass -File "{{ script_path }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        run_level: highest
        state: present
        enabled: yes
        trigger:
          - type: once
            start_boundary: "2025-06-21T10:00:00"  # <-- Hardcoded start time avoids Jinja parsing errors
        execution_time_limit: PT5M

    - name: â–¶ï¸ Run the scheduled task immediately
      win_command: schtasks /run /tn SetWallpaperTask
